name: Docker builds
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  REGISTRY_IMAGE: oblakstudio/timescaledb-mongo-mysql-fdw

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH@x64
        uses: MrSquaare/ssh-setup-action@v2
        with:
          host: runner.oblak.studio
          private-key: ${{ secrets.DOCKER_BUILDER_KEY }}
          private-key-name: docker_builder

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          endpoint: ssh://github-runner@runner.oblak.studio/var/run/docker.sock

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.source="https://github.com/oblakstudio/wcs"
            org.opencontainers.image.authors="Oblak Studio <support@oblak.studio>"
            org.opencontainers.image.title="WooCommerce Sync Service v2"
            org.opencontainers.image.description="Docker Optimized WooSync v2"
            org.opencontainers.image.licenses="MIT"

      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: ./
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=target,push=true,annotation-index-descriptor.org.opencontainers.image.title=WooCommerce Sync Service v2,annotation-index-descriptor.org.opencontainers.image.authors=Oblak Studio <support@oblak.studio>,annotation-index-descriptor.org.opencontainers.image.source=https://github.com/oblakstudio/wcs,annotation-index-descriptor.org.opencontainers.image.description=Docker Optimized WooSync v2,annotation-index-descriptor.org.opencontainers.image.licenses=MIT
          provenance: false
